function R=Reconstruction_on_grad(f1,f2)
[row,col]=size(f1);
xH=zeros(row,col,2);
yH=zeros(row,col,2);
[xH(:,:,1), yH(:,:,1)] = getGradientH(f1(:,:,1),1);
[xH(:,:,2), yH(:,:,2)] = getGradientH(f2(:,:,1),1);
[fxH, fyH] = getFusedGradients(xH,yH);
PoissonOn = 1;  
avg = 0;        
R = ReconstructGradient(fxH,fyH,avg,PoissonOn);